#![allow(unused_variables)]
#![allow(dead_code)]

#[macro_use]
pub mod comdef {
    include!(concat!(env!("OUT_DIR"), "/yaobow_comdef.rs"));

    // Mirror radiance_scripting's services namespace so cross-crate uses of
    // `radiance_scripting::ComObject_*!` macros (which expand `use crate as
    // radiance_scripting`) can resolve `radiance_scripting::comdef::services::*`
    // through this crate.
    pub mod services {
        pub use radiance_scripting::comdef::services::*;
    }

    // Generated comdef for the title-page foreign service surface
    // (`crosscom/idl/yaobow_services.idl`). Paired with the p7 binding
    // exposed via `script_source::YAOBOW_SERVICES_P7`.
    #[macro_use]
    pub mod yaobow_services {
        include!(concat!(env!("OUT_DIR"), "/yaobow_services_comdef.rs"));
    }
}

/// Auto-generated script bridges. The local `yaobow_services` bridge
/// (typed `IYaobowScriptAppClient`, `intern_<i>_arg` helpers,
/// `register_all_protos`) is included from `OUT_DIR`; cross-IDL deps
/// are re-exported under the paths the codegen generates for imported
/// IDL stems (`crate::script_bridges::<idl_stem>::<fn>`).
pub mod script_bridges {
    pub mod yaobow_services {
        include!(concat!(env!("OUT_DIR"), "/yaobow_services_bridge.rs"));
    }

    pub mod radiance {
        pub use radiance_scripting::script_bridges::radiance::*;
    }

    pub mod scripting_services {
        pub use radiance_scripting::script_bridges::scripting_services::*;
    }

    pub mod crosscom {
        pub use radiance_scripting::script_bridges::crosscom::*;
    }

    pub mod openpal4 {
        pub use shared::script_bridges::openpal4::*;
    }

    pub mod pal4_debug {
        pub use shared::script_bridges::pal4_debug::*;
    }
}

pub mod script_source {
    //! p7 script bundle for the yaobow main app. `app.p7` is the only
    //! root source; title and PAL4 debug scripts are sibling modules
    //! reached through the rooted `YaobowScriptApp` object.
    //!
    //! Most per-method dispatch boilerplate (intern + foreign_box +
    //! call + reverse-wrap) is generated by `crosscom-ccidl` from
    //! `crosscom/idl/yaobow_services.idl`'s `[protosept(script_app_root)]`
    //! flag; we just hold the typed client and forward.

    use std::cell::RefCell;
    use std::rc::Rc;

    use crosscom::ComRc;
    use radiance::comdef::{
        IApplication, IApplicationExt, ICameraControl, IDirector, IEntity, IImmediateDirector,
        IRayCaster,
    };
    use radiance::radiance::CoreRadianceEngine;
    use radiance_scripting::comdef::services::IInputService;
    use radiance_scripting::{
        bootstrap_script_root, ScriptHost, ScriptModule, ScriptPackage, HOST_CONTEXT_TYPE_TAG,
    };
    use shared::openpal4::comdef::pal4_debug::{IPal4DebugContext, IPal4DebugOverlay};
    use shared::openpal4::comdef::{
        IPal4ActorAnimationController, IPal4ActorController, IPal4GameContext,
    };
    use shared::openpal4::scene::Pal4ActorControllerFactory;
    use shared::GameType;

    use crate::application::yaobow_app_context::YaobowAppContext;
    use crate::script_bridges::yaobow_services::IYaobowScriptAppClient;
    use radiance_scripting::comdef::services::IHostContext;

    /// p7 binding source for `yaobow_services.idl`. Register it with
    /// `ScriptHost::add_binding("yaobow_services", YAOBOW_SERVICES_P7)`
    /// before loading any yaobow script that imports the module.
    pub const YAOBOW_SERVICES_P7: &str =
        include_str!(concat!(env!("OUT_DIR"), "/yaobow_services.p7"));

    pub const APP_P7: &str = include_str!("../scripts/app.p7");
    pub const PAL4_DEBUG_P7: &str = shared::openpal4::pal4_debug::PAL4_DEBUG_P7;
    pub const ACTOR_CONTROLLER_P7: &str =
        shared::openpal4::actor_controller_script::ACTOR_CONTROLLER_P7;

    pub const IDL_BINDINGS: &[ScriptModule] = &[
        ScriptModule::new("yaobow_services", YAOBOW_SERVICES_P7),
        ScriptModule::new("pal4_debug", PAL4_DEBUG_P7),
        ScriptModule::new(
            "openpal4",
            shared::openpal4::actor_controller_script::OPENPAL4_P7,
        ),
    ];

    /// Sibling modules referenced by `app.p7`.
    pub const SIBLING_MODULES: &[ScriptModule] = &[
        ScriptModule::new("title_consts", include_str!("../scripts/title_consts.p7")),
        ScriptModule::new("title", include_str!("../scripts/title.p7")),
        ScriptModule::new(
            "pal4_debug_overlay",
            include_str!("../scripts/pal4_debug_overlay.p7"),
        ),
        ScriptModule::new("actor_controller", ACTOR_CONTROLLER_P7),
    ];

    pub const YAOBOW_PACKAGE: ScriptPackage = ScriptPackage {
        root_name: "app",
        root_source: APP_P7,
        idl_bindings: IDL_BINDINGS,
        modules: SIBLING_MODULES,
    };

    /// Registers every sibling module with `host` via `add_binding`.
    /// After this, callers load `APP_P7` to compile the app root.
    /// Bindings survive `ScriptHost::reload`, but a host that fully
    /// recreates its `ScriptHost` must call this again.
    pub fn register_yaobow_modules(host: &ScriptHost) {
        for module in YAOBOW_PACKAGE.modules {
            host.add_binding(module.name, module.source);
        }
    }

    pub fn register_yaobow_project(host: &ScriptHost) {
        YAOBOW_PACKAGE
            .validate()
            .expect("yaobow script package manifest must be valid");
        YAOBOW_PACKAGE.register_bindings(host);
    }

    pub fn ensure_yaobow_project_loaded(host: &ScriptHost) {
        YAOBOW_PACKAGE
            .ensure_loaded(host, "init")
            .expect("yaobow app script project must load successfully");
    }

    /// App-lifetime owner of the script host + the rooted script-side
    /// `box<IYaobowScriptApp>` (via the auto-generated typed client).
    /// Cached as an engine service so every per-game loader
    /// (PAL3/PAL4/…) sees the same instance.
    pub struct YaobowScriptProject {
        client: Rc<IYaobowScriptAppClient>,
        selected_game: Rc<RefCell<Option<GameType>>>,
    }

    impl YaobowScriptProject {
        /// App-lifetime install. Constructs the `YaobowAppContext` and
        /// the `selected_game` slot internally, so callers no longer
        /// build their own context. Idempotent — every subsequent call
        /// from any feature (PAL3/PAL4/…) returns the same project.
        pub fn install(
            app: &ComRc<IApplication>,
            config: Rc<RefCell<shared::config::YaobowConfig>>,
        ) -> Rc<Self> {
            let engine_rc = app.engine();
            let engine = engine_rc.borrow();
            Self::install_inner(&engine, || {
                let selected_game: Rc<RefCell<Option<GameType>>> = Rc::new(RefCell::new(None));
                let app_ctx = YaobowAppContext::create(app.clone(), selected_game.clone(), config);
                (app_ctx, selected_game)
            })
        }

        /// Lower-level installer used by tests and integration paths
        /// that build a custom `IHostContext` (e.g. with stub
        /// services). The supplied `selected_game` slot is exposed via
        /// [`Self::selected_game`].
        pub fn install_with_context(
            engine: &CoreRadianceEngine,
            app_ctx: ComRc<IHostContext>,
            selected_game: Rc<RefCell<Option<GameType>>>,
        ) -> Rc<Self> {
            Self::install_inner(engine, || (app_ctx, selected_game))
        }

        fn install_inner<F>(engine: &CoreRadianceEngine, build_ctx: F) -> Rc<Self>
        where
            F: FnOnce() -> (ComRc<IHostContext>, Rc<RefCell<Option<GameType>>>),
        {
            engine.get_or_insert_service(|| {
                let host = ScriptHost::install(engine);
                let (app_ctx, selected_game) = build_ctx();
                let app_data = bootstrap_script_root(
                    &host,
                    &YAOBOW_PACKAGE,
                    app_ctx,
                    HOST_CONTEXT_TYPE_TAG,
                    "init",
                )
                .expect("yaobow app script init must succeed");
                let app = host.root(app_data);
                let client = IYaobowScriptAppClient::new(host, app);
                Self {
                    client,
                    selected_game,
                }
            })
        }

        pub fn host(&self) -> Rc<ScriptHost> {
            self.client.host().clone()
        }

        /// The shared `Rc<RefCell<Option<GameType>>>` slot. Title-side
        /// `IAppService.open_game(ordinal)` writes this slot; the
        /// `YaobowApplicationLoader::on_updating` poll reads and
        /// clears it on the next tick to swap the active per-game
        /// loader.
        pub fn selected_game(&self) -> Rc<RefCell<Option<GameType>>> {
            self.selected_game.clone()
        }

        pub fn make_title_director(&self) -> Result<ComRc<IImmediateDirector>, String> {
            // The script-side conformer lists both `IDirector` and
            // `IImmediateDirector`; the generated client returns the
            // immediate variant directly.
            self.client
                .make_title_director()
                .map_err(|err| format!("{err:?}"))
        }

        pub fn make_title_director_as_director(&self) -> Result<ComRc<IDirector>, String> {
            let imm = self.make_title_director()?;
            imm.query_interface::<IDirector>()
                .ok_or_else(|| "title director did not implement IDirector".to_string())
        }

        pub fn make_pal4_debug_overlay(
            &self,
            ctx: ComRc<IPal4DebugContext>,
        ) -> Result<ComRc<IPal4DebugOverlay>, String> {
            self.client
                .make_pal4_debug_overlay(ctx)
                .map_err(|err| format!("{err:?}"))
        }

        /// Mint a scripted party-wide `IPal4ActorController` covering
        /// all four party members. Thin wrapper over the generated
        /// `IYaobowScriptAppClient::make_actor_controller` that
        /// flattens the `[ComRc<_>; 4]` arrays into the 12 positional
        /// arguments the IDL declares.
        pub fn make_actor_controller(
            &self,
            game_ctx: ComRc<IPal4GameContext>,
            input: ComRc<IInputService>,
            entities: [ComRc<IEntity>; 4],
            anims: [ComRc<IPal4ActorAnimationController>; 4],
            camera: ComRc<ICameraControl>,
            ray_caster: ComRc<IRayCaster>,
        ) -> Result<ComRc<IPal4ActorController>, String> {
            let [e0, e1, e2, e3] = entities;
            let [a0, a1, a2, a3] = anims;
            self.client
                .make_actor_controller(
                    game_ctx, input, e0, e1, e2, e3, a0, a1, a2, a3, camera, ray_caster,
                )
                .map_err(|err| format!("{err:?}"))
        }

        /// Builds an `Rc<dyn Pal4ActorControllerFactory>` suitable for
        /// `Pal4AppContext::set_actor_controller_factory`. The factory
        /// keeps a strong `Rc<YaobowScriptProject>` so the script host
        /// stays installed for the controllers' lifetime.
        pub fn actor_controller_factory(self: &Rc<Self>) -> Rc<dyn Pal4ActorControllerFactory> {
            Rc::new(YaobowActorControllerFactory {
                project: self.clone(),
            })
        }

        /// One-shot helper for PAL4: builds a fresh debug session
        /// (Rust-side context + state) and asks the script app to
        /// create the overlay against it. Returns the bundle the
        /// `OpenPAL4Director` keeps and dispatches each frame.
        pub fn make_pal4_debug_bundle(&self) -> shared::openpal4::director::Pal4DebugBundle {
            let session = shared::openpal4::pal4_debug::create_debug_session();
            let overlay = self
                .make_pal4_debug_overlay(session.context.clone())
                .expect("pal4_debug overlay creation must succeed");
            shared::openpal4::director::Pal4DebugBundle {
                overlay,
                overlay_ctx: session.context,
                debug_state: session.state,
            }
        }
    }

    /// `Pal4ActorControllerFactory` impl that defers to a
    /// `YaobowScriptProject`. Held as `Rc<dyn …>` by `Pal4AppContext`
    /// so the script host stays alive for every minted controller.
    struct YaobowActorControllerFactory {
        project: Rc<YaobowScriptProject>,
    }

    impl Pal4ActorControllerFactory for YaobowActorControllerFactory {
        fn make_actor_controller(
            &self,
            game_ctx: ComRc<IPal4GameContext>,
            input: ComRc<IInputService>,
            entities: [ComRc<IEntity>; 4],
            anims: [ComRc<IPal4ActorAnimationController>; 4],
            camera: ComRc<ICameraControl>,
            ray_caster: ComRc<IRayCaster>,
        ) -> ComRc<IPal4ActorController> {
            self.project
                .make_actor_controller(game_ctx, input, entities, anims, camera, ray_caster)
                .expect("scripted Pal4PartyController creation must succeed")
        }
    }
}

pub mod application;
pub mod opengujian;
pub mod openpal3;
pub mod openpal4;
pub mod openpal5;
pub mod openswd5;

pub use application::run_title_selection;
pub use opengujian::run_opengujian;
pub use openpal3::run_openpal3;
pub use openpal4::application::AgentBootOptions as Pal4AgentBootOptions;
pub use openpal4::{run_openpal4, run_openpal4_with_agent};
pub use openpal5::run_openpal5;
pub use openswd5::run_openswd5;

#[cfg_attr(target_os = "android", ndk_glue::main(backtrace = "on"))]
pub fn android_entry() {
    openpal3::run_openpal3();
}
