[uuid(00000000-0000-0000-C000-000000000046), codegen(ignore)]
interface IUnknown {
    long query_interface(UUID guid, [out] IUnknown retval);
    long add_ref();
    long release();
}

[uuid(6ac46481-7efa-45ff-a279-687b4603c746)]
interface IViewContent: IUnknown {
    void render(longlong scene_manager, longlong ui, float delta_sec);
}

[uuid(6ac46481-7efa-45ff-a279-687b4603c747)]
class ResourceViewContent: IViewContent {}

