module(rust) radiance_editor::comdef;

import radiance.idl;

[uuid(6ac46481-7efa-45ff-a279-687b4603c746)]
interface IViewContent: IUnknown {
    [internal(), rust()]
    crosscom::Void render(&mut dyn radiance::scene::SceneManager scene_manager, &imgui::Ui ui, f32 delta_sec);
}

[uuid(6ac46481-7efa-45ff-a279-687b4603c747)]
class ResourceViewContent: IViewContent {}

[uuid(9a9be0b9-f9bd-4107-99ba-6813d858c464)]
class EditorApplicationLoaderComponent: IApplicationLoaderComponent {}
