module(rust) opengb::comdef;

import crosscom.idl;
import radiance.idl;

[uuid(e11fe493-654a-4072-b883-a7ee1a35a24a)]
interface IRoleController: IComponent {
    [internal(), rust()]
    &'static opengb::scene::RoleController get();
}

[uuid(854b55b6-8054-4c4d-aa76-09e6d3287544)]
class RoleController: IRoleController {}

[uuid(9c6dc3a5-d858-40c0-960b-b3527ad4516f)]
interface ICvdModel: IComponent {}

[uuid(ac6e671f-79fc-4bee-bf31-65fd947d8244)]
class CvdModel: IComponent {}

[uuid(77fe1a3d-05cf-47f9-b80a-08be6d19b0a4)]
interface IScnSceneComponent: IComponent {
    [internal(), rust()]
    &'static opengb::scene::ScnScene get();
}

[uuid(69e2fd84-c679-40c0-9608-9578d1aaecaf)]
class ScnSceneComponent: IScnSceneComponent {}

[uuid(4ca4e74c-c5a9-4356-8aae-19a0af9ac899)]
interface IAdventureDirector: IDirector {
    [internal(), rust()]
    &'static opengb::directors::AdventureDirector get();
}

[uuid(0ac488a6-7d94-4b1d-ae37-8d9365005c7d)]
class AdventureDirector: IAdventureDirector {}
