use std::collections::BTreeMap;
use std::path::PathBuf;

fn main() {
    generate_pair(
        "yaobow_editor_services.idl",
        "yaobow_editor_services_comdef.rs",
        "yaobow_editor_services.p7",
    );
    generate_lucide_icons_module();
    pack_script_bundle();
}

fn generate_comdef(idl_file: &str, out_file: &str) {
    let idl = idl_path(idl_file);
    let out = out_path(out_file);
    let dependencies = crosscom_ccidl::generate_to_file(&idl, &out)
        .unwrap_or_else(|err| panic!("Failed to generate {}: {}", out_file, err));
    for dependency in dependencies {
        println!("cargo:rerun-if-changed={}", dependency.display());
    }
}

fn idl_path(idl_file: &str) -> PathBuf {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("crosscom")
        .join("idl")
        .join(idl_file)
}

fn out_path(out_file: &str) -> PathBuf {
    PathBuf::from(std::env::var("OUT_DIR").unwrap()).join(out_file)
}

fn generate_pair(idl_file: &str, rust_out: &str, p7_out: &str) {
    generate_comdef(idl_file, rust_out);
    let idl = idl_path(idl_file);
    let out = out_path(p7_out);
    let dependencies = crosscom_ccidl::generate_protosept_to_file(&idl, &out)
        .unwrap_or_else(|err| panic!("Failed to generate {}: {}", p7_out, err));
    for dependency in dependencies {
        println!("cargo:rerun-if-changed={}", dependency.display());
    }
}

/// Generates `icons.p7` in `OUT_DIR` from the Lucide codepoint table
/// vendored in `radiance-assets`. The output is a single p7 module of
/// `pub const ICON_<UPPER_SNAKE>: string = "\u{XXXX}";` lines — one per
/// Lucide glyph — so editor scripts can interpolate icons directly into
/// imgui widget labels (`f"{icons.ICON_FOLDER} {name}"`).
fn generate_lucide_icons_module() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let codepoints_path = manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("radiance")
        .join("radiance-assets")
        .join("src")
        .join("embed")
        .join("fonts")
        .join("lucide.codepoints.json");

    println!("cargo:rerun-if-changed={}", codepoints_path.display());

    let raw = std::fs::read_to_string(&codepoints_path).unwrap_or_else(|err| {
        panic!(
            "Failed to read Lucide codepoints from {}: {}",
            codepoints_path.display(),
            err
        )
    });

    // BTreeMap so output ordering is deterministic across rebuilds.
    let codepoints: BTreeMap<String, u32> = serde_json::from_str(&raw)
        .unwrap_or_else(|err| panic!("Failed to parse Lucide codepoints JSON: {}", err));

    let mut out = String::with_capacity(codepoints.len() * 64);
    out.push_str("// Auto-generated by yaobow_editor/build.rs from\n");
    out.push_str("// radiance-assets/src/embed/fonts/lucide.codepoints.json.\n");
    out.push_str("// DO NOT EDIT BY HAND — re-vendor Lucide and rebuild.\n\n");

    for (name, code) in &codepoints {
        let ident = lucide_name_to_ident(name);
        // Escape as \u{XXXX} so the p7 source stays pure ASCII even
        // though the runtime string carries the PUA codepoint.
        out.push_str(&format!(
            "pub let ICON_{}: string = \"\\u{{{:x}}}\";\n",
            ident, code
        ));
    }

    let out_path = out_path("icons.p7");
    std::fs::write(&out_path, out)
        .unwrap_or_else(|err| panic!("Failed to write {}: {}", out_path.display(), err));
}

/// Converts a Lucide icon name (`a-arrow-down`, `3d-printer` etc.) into
/// an UPPER_SNAKE_CASE p7 identifier suffix. Names that would begin
/// with a digit are prefixed with `_` so the result is always a legal
/// p7 identifier.
fn lucide_name_to_ident(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| match c {
            '-' => '_',
            c => c.to_ascii_uppercase(),
        })
        .collect();
    if s.chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        s.insert(0, '_');
    }
    s
}

/// Pack `scripts/*.p7` + generated `yaobow_editor_services.p7` +
/// generated `icons.p7` (both from `OUT_DIR`) into
/// `OUT_DIR/yaobow_editor.ypk`. Root = `main` (i.e. `main.p7` is the
/// app-root script the editor loads). `yaobow_editor_services`
/// registers as an idl_binding; everything else (including `icons`)
/// goes in as a module so script imports stay identical.
fn pack_script_bundle() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let scripts_dir = manifest_dir.join("scripts");
    let out = out_path("yaobow_editor.ypk");

    let services_path = out_path("yaobow_editor_services.p7");
    let icons_path = out_path("icons.p7");

    let extra_files = [
        script_package::ExtraFile {
            source_path: services_path.as_path(),
            virtual_entry: "yaobow_editor_services.p7",
        },
        script_package::ExtraFile {
            source_path: icons_path.as_path(),
            virtual_entry: "icons.p7",
        },
    ];

    script_package::pack(
        &script_package::PackInput {
            scripts_dir: &scripts_dir,
            extra_files: &extra_files,
        },
        &out,
    )
    .unwrap_or_else(|err| panic!("Failed to pack yaobow_editor scripts: {err}"));
}
