module(rust) test::crosscom_gen;

import crosscom.idl;

[uuid(6ac46481-7efa-45ff-a279-687b4603c746)]
interface ITest: IUnknown {
    int test();
}

[uuid(de3d989d-2b1d-42a3-b085-a23e40840126)]
interface ITest2: ITest {
    float mul(int a, float b);
}

[uuid(de3d989d-2b1d-42a3-b085-a23e40840128)]
interface ITest3: IUnknown {
    int echo(int a);
}

[uuid(de3d989d-2b1d-42a3-b085-a23e40840129)]
interface ITest4: IUnknown {
    ITest3 get();
}

[uuid(50203ee6-e472-42ba-bd57-a202e9cafe7f)]
class Test: ITest2, ITest, ITest3, ITest4 {}
